# Generated by Django 3.0.7 on 2021-11-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(default=None, max_length=10)),
                ('import_date', models.DateField()),
                ('model', models.CharField(default=None, max_length=10)),
                ('make', models.CharField(default=None, max_length=10)),
                ('color', models.CharField(default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'ImportedCar',
                'verbose_name_plural': 'ImportedCars',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=150, unique=True)),
                ('part_name', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, default=None, max_length=100)),
                ('barcode', models.IntegerField(default=283946105, unique=True)),
                ('note', models.TextField(default=None)),
                ('selling_price', models.IntegerField(default=0)),
                ('amount_in_stock', models.IntegerField(default=1)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ERP.ImportedCars')),
                ('part_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ERP.Parts')),
            ],
        ),
    ]
