# Generated by Django 3.0.7 on 2021-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=878169328, unique=True),
        ),
    ]
