# Generated by Django 3.0.7 on 2021-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20211114_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(default=0)),
                ('part_number_id', models.IntegerField(default=0)),
                ('barcode', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=262867807, unique=True),
        ),
    ]
