# Generated by Django 3.0.7 on 2021-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20211114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='note',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=724413765, unique=True),
        ),
    ]
