# Generated by Django 3.2.9 on 2021-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20211114_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcars',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=556814290, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
