# Generated by Django 3.2.9 on 2021-11-21 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20211115_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 21, 12, 23, 48, 624365)),
        ),
        migrations.AddField(
            model_name='stock',
            name='shelf',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=332699432, unique=True),
        ),
    ]
