# Generated by Django 3.2.9 on 2021-11-21 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20211121_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sell_date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.IntegerField(default=570645130, unique=True),
        ),
    ]
